-- =====================================================
-- DATABASE & SCHEMAS
-- =====================================================

CREATE DATABASE IF NOT EXISTS MOVIES;

USE DATABASE MOVIES;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CORE;
CREATE SCHEMA IF NOT EXISTS MART;
CREATE SCHEMA IF NOT EXISTS MONITORING;


-- =====================================================
-- WAREHOUSES
-- =====================================================

CREATE OR REPLACE WAREHOUSE INGEST_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = 'Warehouse for ingestion workloads';

CREATE OR REPLACE WAREHOUSE TRANSFORM_WH
WAREHOUSE_SIZE = 'SMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = 'Warehouse for transformations, dbt, and pipelines';

CREATE OR REPLACE WAREHOUSE BI_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 120
AUTO_RESUME = TRUE
MAX_CLUSTER_COUNT = 3
MIN_CLUSTER_COUNT = 1
SCALING_POLICY = 'STANDARD'
INITIALLY_SUSPENDED = TRUE
COMMENT = 'Warehouse for BI queries and analyst workloads';


-- =====================================================
-- ROLES
-- =====================================================

CREATE ROLE IF NOT EXISTS PLATFORM_ADMIN;
CREATE ROLE IF NOT EXISTS DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS ANALYST;

-- Role hierarchy
GRANT ROLE DATA_ENGINEER TO ROLE PLATFORM_ADMIN;
GRANT ROLE ANALYST TO ROLE PLATFORM_ADMIN;


-- =====================================================
-- DATABASE PRIVILEGES
-- =====================================================

GRANT OWNERSHIP ON DATABASE MOVIES TO ROLE PLATFORM_ADMIN COPY CURRENT GRANTS;

GRANT USAGE ON DATABASE MOVIES TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE MOVIES TO ROLE ANALYST;


-- =====================================================
-- SCHEMA OWNERSHIP
-- =====================================================

GRANT OWNERSHIP ON SCHEMA MOVIES.RAW TO ROLE PLATFORM_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA MOVIES.CORE TO ROLE PLATFORM_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA MOVIES.MART TO ROLE PLATFORM_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA MOVIES.MONITORING TO ROLE PLATFORM_ADMIN COPY CURRENT GRANTS;


-- =====================================================
-- SCHEMA USAGE
-- =====================================================

GRANT USAGE ON ALL SCHEMAS IN DATABASE MOVIES TO ROLE DATA_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE MOVIES TO ROLE ANALYST;


-- =====================================================
-- ENGINEER OBJECT CREATION PRIVILEGES
-- =====================================================

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE STREAM, CREATE TASK
ON SCHEMA MOVIES.RAW TO ROLE DATA_ENGINEER;

GRANT CREATE TABLE, CREATE VIEW, CREATE STREAM, CREATE TASK
ON SCHEMA MOVIES.CORE TO ROLE DATA_ENGINEER;

GRANT CREATE TABLE, CREATE VIEW
ON SCHEMA MOVIES.MART TO ROLE DATA_ENGINEER;

GRANT CREATE SCHEMA ON DATABASE MOVIES TO ROLE DATA_ENGINEER;


-- =====================================================
-- ANALYST ACCESS (CURRENT + FUTURE OBJECTS)
-- =====================================================

-- Existing objects
GRANT SELECT ON ALL TABLES IN SCHEMA MOVIES.MART TO ROLE ANALYST;
GRANT SELECT ON ALL VIEWS  IN SCHEMA MOVIES.MART TO ROLE ANALYST;

-- Future objects
GRANT SELECT ON FUTURE TABLES IN SCHEMA MOVIES.MART TO ROLE ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA MOVIES.MART TO ROLE ANALYST;


-- =====================================================
-- WAREHOUSE ACCESS
-- =====================================================

GRANT USAGE ON WAREHOUSE INGEST_WH TO ROLE PLATFORM_ADMIN;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE PLATFORM_ADMIN;
GRANT USAGE ON WAREHOUSE BI_WH TO ROLE PLATFORM_ADMIN;

GRANT USAGE ON WAREHOUSE INGEST_WH TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE BI_WH TO ROLE ANALYST;


-- =====================================================
-- ASSIGN ROLES TO YOUR USER
-- =====================================================

GRANT ROLE PLATFORM_ADMIN TO USER ADIGOTCERTIFIED;
--GRANT ROLE DATA_ENGINEER TO USER <your_user>;

-- USE ROLE PLATFORM_ADMIN;


