version: 2

models:

  - name: dim_users
    columns:
      - name: user_id
        tests: [not_null, unique]

  - name: dim_movies
    columns:
      - name: movie_id
        tests: [not_null, unique]

  - name: fact_viewing
    columns:
      - name: event_id
        tests: [not_null, unique]
      - name: user_id
        tests:
          - relationships:
              to: ref('dim_users')
              field: user_id