version: 2

sources:
  - name: raw
    database: YOUR_DATABASE
    schema: raw
    tables:
      - name: raw_users
      - name: raw_movies
      - name: raw_subscriptions
      - name: raw_view_events